FROM xalwart/gtest:1.11.0-clang-10-alpine-3.13

FROM xalwart/framework:0.0.0-alpine

WORKDIR /app

# Copy google test framework
COPY --from=0 /usr/local /usr/local

COPY ./src ./src
COPY ./tests ./tests
COPY ./CMakeLists.txt .
COPY ./scripts/test.sh ./scripts/test.sh

CMD ["bash"]
