# Copyright (c) 2021 Yuriy Lisovskiy

debug: true

allowed_hosts:
  - 127.0.0.1
  - ::1

modules:
  - RootModuleConfig
  - OAuthModuleConfig
  - UsersModuleConfig

middleware:
  - xw::middleware::Security
  - xw::middleware::Common
  - xw::middleware::XFrameOptions

databases:
  - instance: default
    dbms: sqlite3
    file: db.sqlite3
    connections: 3

logger:
  use_colors: true
  levels: '*'

limits:
  data_upload_max_memory_size: 20971520
  file_upload_max_memory_size: 104857600

oauth:
  jwt:
    subject: 'oauth'
    issuer: 'oauth-service'
    token_type: 'Bearer'
    period:
      minutes: 10
  signer:
    algorithm: HS256
    secret_key: 'set in local settings'
