name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Test the application
    runs-on: ubuntu-18.04
    env:
      CONTAINER_NAME: oauth-service:test
    steps:
      - uses: actions/checkout@v2
      - name: Build test container
        run: |
          sudo docker build -t ${{ env.CONTAINER_NAME }} -f Dockerfile.test .
      - name: Run test container
        run: |
          sudo docker run -i ${{ env.CONTAINER_NAME }} bash ./scripts/test.sh alpine clang
